services:
    nanomq:
        image: emqx/nanomq:latest
        container_name: nanomq_broker
        ports:
            - '1883:1883'
        networks:
            - iotnet

    # node_subscriber:
    #   build: ./node_app
    #   container_name: node_subscriber
    #   networks:
    #     - iotnet
    #   depends_on:
    #     - nanomq
    #   command: ["node", "dist/subscriber.js"]
    # node_publisher:
    #   build: ./node_app
    #   container_name: node_publisher
    #   networks:
    #     - iotnet
    #   depends_on:
    #     - nanomq
    #   command: ["node", "dist/publisher.js"]

    node_app:
        build: ./node_app
        container_name: node_app
        depends_on:
            - nanomq
        networks:
            - iotnet

networks:
    iotnet:
        driver: bridge
