services:
  nanomq:
    image: emqx/nanomq:latest
    container_name: nanomq_broker
    ports:
      - "1883:1883"
    networks:
      - iotnet

  node_io:
    build:
      context: ./node_app
      dockerfile: Dockerfile.io
    container_name: node_io
    networks:
      - iotnet
    depends_on:
      - nanomq
    environment:
      BROKER_URL: mqtt://nanomq:1883

  node_controller:
    build:
      context: ./node_app
      dockerfile: Dockerfile.controller
    container_name: node_controller
    networks:
      - iotnet
    depends_on:
      - nanomq
    environment:
      BROKER_URL: mqtt://nanomq:1883

networks:
  iotnet:
    driver: bridge
